modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="monsters_level_up"
version="1.2"
displayName="Monsters Level Up"
displayURL="https://www.curseforge.com/minecraft/mc-mods/monsters-level-up"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Sombrius"
description="A mod that makes mobs level up alongside the player"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.monsters_level_up]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.monsters_level_up]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration